### ISSUE TITLE
Building wheel for plone.app.themingplugins (pyproject.toml) ... error

### ISSUE THREAD

**Issue by arky** [plone/plone.app.themingplugins#8]
Installing themingplugins in gnu/Linux 686 machine with python 3.10 results in following error.

```

Building wheels for collected packages: plone.app.themingplugins
  Building wheel for plone.app.themingplugins (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/arky/Code/Plone/Plone-6/backend/bin/python /home/arky/Code/Plone/Plone-6/backend/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpkmzus2vd
       cwd: /tmp/pip-install-0l6cubfd/plone-app-themingplugins_2d6c99c841ec4435bfacef04442f284f
  Complete output (32 lines):
  Traceback (most recent call last):
    File "/home/arky/Code/Plone/Plone-6/backend/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/home/arky/Code/Plone/Plone-6/backend/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/arky/Code/Plone/Plone-6/backend/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/tmp/pip-build-env-2o78139w/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 244, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/tmp/pip-build-env-2o78139w/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 229, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-2o78139w/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 281, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-2o78139w/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 174, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 7, in <module>
      setup(
    File "/tmp/pip-build-env-2o78139w/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
      return distutils.core.setup(**attrs)
    File "/tmp/pip-build-env-2o78139w/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 109, in setup
      _setup_distribution = dist = klass(attrs)
    File "/tmp/pip-build-env-2o78139w/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 477, in __init__
      _Distribution.__init__(
    File "/tmp/pip-build-env-2o78139w/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 293, in __init__
      self.finalize_options()
    File "/tmp/pip-build-env-2o78139w/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 901, in finalize_options
      ep(self)
    File "/tmp/pip-build-env-2o78139w/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 922, in _finalize_setup_keywords
      ep.load()(self, ep.name, value)
    File "/tmp/pip-build-env-2o78139w/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 287, in check_nsp
      warnings.warn(msg, SetuptoolsDeprecationWarning)
  TypeError: expected string or bytes-like object
  ----------------------------------------
  ERROR: Failed building wheel for plone.app.themingplugins
Failed to build plone.app.themingplugins
ERROR: Could not build wheels for plone.app.themingplugins, which is required to install pyproject.toml-based projects

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04 LTS
Release:	22.04
Codename:	jammy

**Comment by gotcha** [comment]
I just made a new 1.2 release which includes a wheel.

Does that address your issue ?
